version: "3.9"

services:
  web:
    build: .
    ports:
      - "5001:8000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis_data:/bitnami/redis/data"
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
    driver: local
