version: "3.9"

services:
  web:
    build: .
    ports:
      - "5001:80"
    env_file: .env
    depends_on:
      - memcached

  memcached:
    image: "memcached:alpine"
    command:
      - memcached
      - --memory-limit=512
