version: "3.9"

services:
  web:
    build: .
    ports:
      - "5001:80"
    environment:
      - CACHE_EXPIRATION_SECONDS=${CACHE_EXPIRATION_SECONDS}
      - ENV=${ENV}
      - FOTOWARE_CLIENT_ID=${FOTOWARE_CLIENT_ID}
      - FOTOWARE_CLIENT_SECRET=${FOTOWARE_CLIENT_SECRET}
      - FOTOWARE_EXPORT_PRESET_GUID=${FOTOWARE_EXPORT_PRESET_GUID}
      - FOTOWARE_HOST=${FOTOWARE_HOST}
      - FOTOWARE_PREFERRED_ARCHIVE=${FOTOWARE_PREFERRED_ARCHIVE}
      - FOTOWARE_SEARCH_EXPRESSION_SUFFIX=${FOTOWARE_SEARCH_EXPRESSION_SUFFIX}
      - NAME=${NAME}
      - RATE_LIMIT=${RATE_LIMIT}

  redis:
    image: "redis:alpine"
    volumes:
      - ./.cache/redis:/data
